// ===================================================
// CATALOGUE COMPLET IRELANCE - PRODUITS AUTHENTIQUES
// ===================================================
// Base de données complète des produits des marques partenaires

import { Product, ProductCategory } from '../types';
import { getProductImagesByName, getMainProductImage } from '../utils/productImages';

/**
 * Catégories de produits disponibles chez irelance
 */
export const CATEGORIES = [
  { id: 'all', name: 'Toutes les Catégories' },
  { id: 'cameras', name: 'Caméras de Surveillance' },
  { id: 'climatisation', name: 'Climatisation' },
  { id: 'securite', name: 'Systèmes de Sécurité' },
  { id: 'solaire', name: 'Panneaux Solaires' },
  { id: 'pc', name: 'PC Portables' },
  { id: 'ordinateurs', name: 'Ordinateurs de Bureau' },
  { id: 'incendie', name: 'Systèmes d\'Incendie' },
  { id: 'electronique', name: 'Matériels Électroniques' }
];

/**
 * Catalogue complet des produits irelance
 * 38 produits authentiques des marques partenaires
 */
export const IRELANCE_PRODUCTS: Product[] = [
  
  // ===== CAMÉRAS DE SURVEILLANCE HIKVISION =====
  {
    id: 'hikvision-ds-2cd2143g0-i-4mp',
    name: 'Caméra IP Hikvision DS-2CD2143G0-I 4MP',
    brand: 'Hikvision',
    category: 'cameras',
    price: 1299.99,
    originalPrice: 1499.99,
    sku: 'HIK-DS2CD2143G0I-4MP',
    description: 'Caméra dôme IP 4MP avec vision nocturne IR 30m, détection de mouvement intelligente et résistance aux intempéries IP67. Idéale pour surveillance intérieure et extérieure.',
    shortDescription: 'Caméra dôme IP 4MP Hikvision avec vision nocturne 30m',
    images: getProductImagesByName('Caméra IP Hikvision DS-2CD2143G0-I 4MP'),
    mainImage: getMainProductImage('Caméra IP Hikvision DS-2CD2143G0-I 4MP'),
    inStock: true,
    stockQuantity: 25,
    specifications: {
      resolution: '4MP (2688×1520)',
      objectif: '2.8mm fixe',
      visionNocturne: '30m IR',
      alimentation: 'PoE+ / 12V DC',
      protection: 'IP67',
      compression: 'H.265+/H.264+'
    },
    features: ['4MP Ultra HD', 'Vision nocturne 30m', 'Détection intelligente', 'Résistant aux intempéries IP67', 'PoE+'],
    tags: ['hikvision', 'dome', '4mp', 'ip67', 'poe', 'surveillance'],
    rating: 4.7,
    reviewCount: 89,
    warranty: '3 ans constructeur',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    isActive: true,
    isFeatured: true,
    promotionPercentage: 13
  },

  {
    id: 'hikvision-ptz-ds-2de4225iw-de',
    name: 'Caméra PTZ Hikvision DS-2DE4225IW-DE 2MP',
    brand: 'Hikvision',
    category: 'cameras',
    price: 2899.99,
    sku: 'HIK-DS2DE4225IWDE-PTZ',
    description: 'Caméra PTZ IP 2MP avec zoom optique 25x, rotation 360°, vision nocturne IR 100m et fonctions de suivi automatique. Parfaite pour surveillance de grandes zones.',
    shortDescription: 'Caméra PTZ IP 2MP avec zoom 25x et rotation 360°',
    images: getProductImagesByName('Caméra PTZ Hikvision DS-2DE4225IW-DE 2MP'),
    mainImage: getMainProductImage('Caméra PTZ Hikvision DS-2DE4225IW-DE 2MP'),
    inStock: true,
    stockQuantity: 8,
    specifications: {
      resolution: '2MP (1920×1080)',
      zoom: '25x optique',
      rotation: '360° horizontal, 90° vertical',
      visionNocturne: '100m IR',
      vitesseRotation: '120°/s',
      presets: '300 positions'
    },
    features: ['Zoom 25x', 'Rotation 360°', 'Suivi automatique', 'Vision nocturne 100m', 'Contrôle à distance'],
    tags: ['hikvision', 'ptz', 'zoom', 'rotation', 'tracking'],
    rating: 4.8,
    reviewCount: 34,
    warranty: '3 ans constructeur',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'hikvision-kit-nvr-8ch',
    name: 'Kit NVR Hikvision 8 canaux + 4 caméras IP',
    brand: 'Hikvision',
    category: 'cameras',
    price: 4599.99,
    originalPrice: 5299.99,
    sku: 'HIK-KIT-NVR8-4CAM',
    description: 'Kit complet de surveillance avec NVR 8 canaux, 4 caméras IP 4MP, disque dur 1TB, câbles et accessoires. Solution clé en main pour sécuriser votre propriété.',
    shortDescription: 'Kit surveillance complet NVR 8CH + 4 caméras 4MP',
    images: getProductImagesByName('Kit NVR Hikvision 8 canaux + 4 caméras IP'),
    mainImage: getMainProductImage('Kit NVR Hikvision 8 canaux + 4 caméras IP'),
    inStock: true,
    stockQuantity: 12,
    specifications: {
      nvr: '8 canaux PoE intégré',
      cameras: '4x caméras IP 4MP',
      stockage: 'HDD 1TB inclus',
      resolution: '4MP par caméra',
      acces: 'Application mobile',
      garantie: '3 ans'
    },
    features: ['Kit complet', '4 caméras 4MP', 'NVR 8 canaux', 'HDD 1TB inclus', 'App mobile', 'Installation facile'],
    tags: ['hikvision', 'kit', 'nvr', '8ch', 'complet', 'surveillance'],
    rating: 4.9,
    reviewCount: 156,
    warranty: '3 ans constructeur',
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
    isActive: true,
    isFeatured: true,
    promotionPercentage: 13
  },

  {
    id: 'hikvision-bullet-8mp',
    name: 'Caméra Bullet Hikvision DS-2CD2T85G1-I8 8MP',
    brand: 'Hikvision',
    category: 'cameras',
    price: 1899.99,
    sku: 'HIK-DS2CD2T85G1I8-8MP',
    description: 'Caméra bullet IP 8MP Ultra HD avec vision nocturne IR 80m, objectif motorisé et fonctions d\'analyse vidéo avancées. Qualité d\'image exceptionnelle.',
    shortDescription: 'Caméra bullet IP 8MP avec vision nocturne 80m',
    images: getProductImagesByName('Caméra Bullet Hikvision DS-2CD2T85G1-I8 8MP'),
    mainImage: getMainProductImage('Caméra Bullet Hikvision DS-2CD2T85G1-I8 8MP'),
    inStock: true,
    stockQuantity: 18,
    specifications: {
      resolution: '8MP (3840×2160)',
      objectif: '2.8-12mm motorisé',
      visionNocturne: '80m IR',
      protection: 'IP67',
      alimentation: 'PoE++',
      analyse: 'Détection ligne/zone'
    },
    features: ['8MP 4K Ultra HD', 'Vision nocturne 80m', 'Objectif motorisé', 'Analyse vidéo', 'IP67'],
    tags: ['hikvision', 'bullet', '8mp', '4k', 'motorise'],
    rating: 4.6,
    reviewCount: 67,
    warranty: '3 ans constructeur',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'hikvision-fisheye-360',
    name: 'Caméra Fisheye Hikvision DS-2CD2955FWD-IS',
    brand: 'Hikvision',
    category: 'cameras',
    price: 2199.99,
    sku: 'HIK-DS2CD2955FWDIS-360',
    description: 'Caméra fisheye 5MP avec vue panoramique 360°, déwarping en temps réel et audio bidirectionnel. Surveillance complète d\'une pièce avec une seule caméra.',
    shortDescription: 'Caméra fisheye 5MP avec vue panoramique 360°',
    images: getProductImagesByName('Caméra Fisheye Hikvision DS-2CD2955FWD-IS'),
    mainImage: getMainProductImage('Caméra Fisheye Hikvision DS-2CD2955FWD-IS'),
    inStock: true,
    stockQuantity: 6,
    specifications: {
      resolution: '5MP (2560×1920)',
      vue: '360° panoramique',
      objectif: '1.29mm fisheye',
      audio: 'Bidirectionnel',
      dewarping: 'Temps réel',
      montage: 'Plafond/mur'
    },
    features: ['Vue 360°', '5MP haute résolution', 'Audio bidirectionnel', 'Déwarping temps réel', 'Installation flexible'],
    tags: ['hikvision', 'fisheye', '360', 'panoramique', 'audio'],
    rating: 4.5,
    reviewCount: 23,
    warranty: '3 ans constructeur',
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'hikvision-kit-nvr-16ch',
    name: 'Kit NVR Hikvision 16 canaux + 8 caméras',
    brand: 'Hikvision',
    category: 'cameras',
    price: 7899.99,
    originalPrice: 8999.99,
    sku: 'HIK-KIT-NVR16-8CAM',
    description: 'Kit professionnel avec NVR 16 canaux PoE, 8 caméras IP 4MP, disque dur 2TB, switch PoE et tous les accessoires. Solution complète pour grandes installations.',
    shortDescription: 'Kit professionnel NVR 16CH + 8 caméras 4MP',
    images: getProductImagesByName('Kit NVR Hikvision 16 canaux + 8 caméras'),
    mainImage: getMainProductImage('Kit NVR Hikvision 16 canaux + 8 caméras'),
    inStock: true,
    stockQuantity: 5,
    specifications: {
      nvr: '16 canaux PoE intégré',
      cameras: '8x caméras IP 4MP',
      stockage: 'HDD 2TB inclus',
      switch: 'PoE 16 ports inclus',
      bande: '160Mbps',
      extensible: 'Jusqu\'à 16 caméras'
    },
    features: ['Kit professionnel', '8 caméras 4MP', 'NVR 16 canaux', 'HDD 2TB', 'Switch PoE inclus', 'Extensible'],
    tags: ['hikvision', 'kit', 'nvr', '16ch', 'professionnel'],
    rating: 4.8,
    reviewCount: 78,
    warranty: '3 ans constructeur',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    isActive: true,
    isFeatured: true,
    promotionPercentage: 12
  },

  // ===== CLIMATISATION LG & SAMSUNG =====
  {
    id: 'lg-dual-cool-inverter-12k',
    name: 'Climatiseur LG Dual Cool Inverter 12000 BTU',
    brand: 'LG',
    category: 'climatisation',
    price: 3299.99,
    originalPrice: 3799.99,
    sku: 'LG-DUAL-COOL-12K',
    description: 'Climatiseur split mural LG avec technologie Dual Inverter, refroidissement rapide, économie d\'énergie classe A++ et contrôle WiFi via application mobile.',
    shortDescription: 'Climatiseur LG Dual Inverter 12000 BTU WiFi',
    images: getProductImagesByName('Climatiseur LG Dual Cool Inverter 12000 BTU'),
    mainImage: getMainProductImage('Climatiseur LG Dual Cool Inverter 12000 BTU'),
    inStock: true,
    stockQuantity: 15,
    specifications: {
      puissance: '12000 BTU/h',
      technologie: 'Dual Inverter',
      efficacite: 'Classe A++',
      surface: '25-35 m²',
      bruit: '19 dB(A)',
      wifi: 'LG ThinQ'
    },
    features: ['Dual Inverter', 'WiFi LG ThinQ', 'Classe A++', 'Ultra silencieux', 'Refroidissement rapide'],
    tags: ['lg', 'climatiseur', 'inverter', '12000btu', 'wifi'],
    rating: 4.6,
    reviewCount: 234,
    warranty: '5 ans compresseur, 2 ans pièces',
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
    isActive: true,
    isFeatured: true,
    promotionPercentage: 13
  },

  {
    id: 'samsung-windfree-18k',
    name: 'Climatiseur Samsung Wind-Free 18000 BTU',
    brand: 'Samsung',
    category: 'climatisation',
    price: 4599.99,
    sku: 'SAM-WINDFREE-18K',
    description: 'Climatiseur Samsung avec technologie Wind-Free, refroidissement sans courant d\'air direct, Digital Inverter et contrôle SmartThings pour un confort optimal.',
    shortDescription: 'Climatiseur Samsung Wind-Free 18000 BTU sans courant d\'air',
    images: getProductImagesByName('Climatiseur Samsung Wind-Free 18000 BTU'),
    mainImage: getMainProductImage('Climatiseur Samsung Wind-Free 18000 BTU'),
    inStock: true,
    stockQuantity: 10,
    specifications: {
      puissance: '18000 BTU/h',
      technologie: 'Wind-Free + Digital Inverter',
      surface: '35-50 m²',
      bruit: '16 dB(A)',
      smart: 'SmartThings',
      filtration: 'HD Filter'
    },
    features: ['Technologie Wind-Free', 'Digital Inverter', 'SmartThings', 'Ultra silencieux', 'Filtration HD'],
    tags: ['samsung', 'windfree', '18000btu', 'smartthings', 'inverter'],
    rating: 4.7,
    reviewCount: 167,
    warranty: '5 ans compresseur, 2 ans pièces',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'lg-artcool-gallery-9k',
    name: 'Climatiseur LG ArtCool Gallery 9000 BTU',
    brand: 'LG',
    category: 'climatisation',
    price: 4299.99,
    sku: 'LG-ARTCOOL-GALLERY-9K',
    description: 'Climatiseur design LG ArtCool Gallery avec façade personnalisable, technologie Inverter, purification d\'air et design ultra-plat pour intégration parfaite.',
    shortDescription: 'Climatiseur design LG ArtCool avec façade personnalisable',
    images: getProductImagesByName('Climatiseur LG ArtCool Gallery 9000 BTU'),
    mainImage: getMainProductImage('Climatiseur LG ArtCool Gallery 9000 BTU'),
    inStock: true,
    stockQuantity: 7,
    specifications: {
      puissance: '9000 BTU/h',
      design: 'ArtCool Gallery',
      epaisseur: '15.9 cm ultra-plat',
      surface: '20-30 m²',
      purification: 'Plasmaster Ionizer',
      facade: 'Personnalisable'
    },
    features: ['Design Gallery', 'Façade personnalisable', 'Ultra-plat', 'Purification air', 'Inverter'],
    tags: ['lg', 'artcool', 'design', '9000btu', 'gallery'],
    rating: 4.8,
    reviewCount: 92,
    warranty: '5 ans compresseur, 2 ans pièces',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'samsung-triangle-24k',
    name: 'Samsung AR7500M Triangle 24000 BTU',
    brand: 'Samsung',
    category: 'climatisation',
    price: 5899.99,
    sku: 'SAM-AR7500M-TRIANGLE-24K',
    description: 'Climatiseur Samsung Triangle avec design unique, refroidissement 43% plus rapide, Digital Inverter 8-Pole et Easy Filter Plus pour un entretien simplifié.',
    shortDescription: 'Climatiseur Samsung Triangle 24000 BTU design unique',
    images: getProductImagesByName('Samsung AR7500M Triangle 24000 BTU'),
    mainImage: getMainProductImage('Samsung AR7500M Triangle 24000 BTU'),
    inStock: true,
    stockQuantity: 8,
    specifications: {
      puissance: '24000 BTU/h',
      design: 'Triangle unique',
      refroidissement: '43% plus rapide',
      surface: '50-70 m²',
      inverter: 'Digital 8-Pole',
      filtre: 'Easy Filter Plus'
    },
    features: ['Design Triangle', 'Refroidissement rapide', 'Digital Inverter 8-Pole', 'Easy Filter', 'Grande surface'],
    tags: ['samsung', 'triangle', '24000btu', 'design', 'rapide'],
    rating: 4.5,
    reviewCount: 45,
    warranty: '5 ans compresseur, 2 ans pièces',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'lg-vrv-multisplit-48k',
    name: 'LG VRV Multi-Split 5 zones 48000 BTU',
    brand: 'LG',
    category: 'climatisation',
    price: 12999.99,
    sku: 'LG-VRV-MULTI-48K-5Z',
    description: 'Système VRV LG multi-split pour 5 zones indépendantes, contrôle individuel par zone, haute efficacité énergétique et installation flexible pour grandes surfaces.',
    shortDescription: 'Système VRV LG multi-split 5 zones 48000 BTU',
    images: getProductImagesByName('LG VRV Multi-Split 5 zones 48000 BTU'),
    mainImage: getMainProductImage('LG VRV Multi-Split 5 zones 48000 BTU'),
    inStock: true,
    stockQuantity: 3,
    specifications: {
      puissance: '48000 BTU/h',
      zones: '5 zones indépendantes',
      type: 'VRV Multi-Split',
      surface: '120-200 m²',
      controle: 'Individuel par zone',
      efficacite: 'SEER > 6.0'
    },
    features: ['5 zones indépendantes', 'Contrôle individuel', 'Haute efficacité', 'Installation flexible', 'VRV'],
    tags: ['lg', 'vrv', 'multisplit', '5zones', '48000btu'],
    rating: 4.9,
    reviewCount: 28,
    warranty: '5 ans compresseur, 3 ans pièces',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'samsung-cassette-4voies-36k',
    name: 'Samsung Cassette 4 voies 36000 BTU',
    brand: 'Samsung',
    category: 'climatisation',
    price: 8799.99,
    sku: 'SAM-CASSETTE-4V-36K',
    description: 'Climatiseur cassette Samsung 4 voies pour faux plafond, diffusion d\'air optimale, Digital Inverter et panneau décoratif blanc élégant pour intégration discrète.',
    shortDescription: 'Climatiseur cassette Samsung 4 voies 36000 BTU',
    images: getProductImagesByName('Samsung Cassette 4 voies 36000 BTU'),
    mainImage: getMainProductImage('Samsung Cassette 4 voies 36000 BTU'),
    inStock: true,
    stockQuantity: 4,
    specifications: {
      puissance: '36000 BTU/h',
      type: 'Cassette 4 voies',
      diffusion: '360° optimale',
      surface: '80-120 m²',
      panneau: 'Décoratif blanc',
      installation: 'Faux plafond'
    },
    features: ['Cassette 4 voies', 'Diffusion 360°', 'Faux plafond', 'Panneau décoratif', 'Digital Inverter'],
    tags: ['samsung', 'cassette', '4voies', '36000btu', 'plafond'],
    rating: 4.4,
    reviewCount: 31,
    warranty: '5 ans compresseur, 2 ans pièces',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    isActive: true,
    isFeatured: false
  },

  // ===== PC PORTABLES DELL, ASUS, ACER =====
  {
    id: 'dell-latitude-5520-i7',
    name: 'Dell Latitude 5520 15.6" Intel i7',
    brand: 'Dell',
    category: 'pc',
    price: 12999.99,
    originalPrice: 14999.99,
    sku: 'DELL-LAT5520-I7',
    description: 'Laptop professionnel Dell Latitude avec processeur Intel Core i7-1165G7, 16GB RAM, SSD 512GB, écran FHD 15.6" et sécurité entreprise avancée.',
    shortDescription: 'Laptop Dell Latitude 15.6" Intel i7 16GB RAM',
    images: getProductImagesByName('Dell Latitude 5520 15.6" Intel i7'),
    mainImage: getMainProductImage('Dell Latitude 5520 15.6" Intel i7'),
    inStock: true,
    stockQuantity: 18,
    specifications: {
      processeur: 'Intel Core i7-1165G7',
      ram: '16GB DDR4',
      stockage: 'SSD 512GB NVMe',
      ecran: '15.6" FHD (1920x1080)',
      graphique: 'Intel Iris Xe',
      connectivite: 'WiFi 6, Bluetooth 5.1'
    },
    features: ['Intel i7 11ème gen', 'Écran FHD', '16GB RAM', 'SSD 512GB', 'WiFi 6', 'Sécurité entreprise'],
    tags: ['dell', 'latitude', 'i7', 'professionnel', 'business'],
    rating: 4.6,
    reviewCount: 145,
    warranty: '3 ans constructeur',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    isActive: true,
    isFeatured: true,
    promotionPercentage: 13
  },

  {
    id: 'asus-zenbook-14-oled-i5',
    name: 'ASUS ZenBook 14 OLED Intel i5',
    brand: 'Asus',
    category: 'pc',
    price: 8999.99,
    sku: 'ASUS-ZB14-OLED-I5',
    description: 'Ultrabook ASUS ZenBook avec écran OLED 14" 2.8K, processeur Intel Core i5-1240P, 16GB RAM, design ultra-fin et autonomie exceptionnelle.',
    shortDescription: 'Ultrabook ASUS ZenBook 14" OLED Intel i5',
    images: getProductImagesByName('ASUS ZenBook 14 OLED Intel i5'),
    mainImage: getMainProductImage('ASUS ZenBook 14 OLED Intel i5'),
    inStock: true,
    stockQuantity: 22,
    specifications: {
      processeur: 'Intel Core i5-1240P',
      ram: '16GB LPDDR5',
      stockage: 'SSD 512GB PCIe 4.0',
      ecran: '14" OLED 2.8K (2880x1800)',
      poids: '1.39 kg',
      autonomie: 'Jusqu\'à 12h'
    },
    features: ['Écran OLED 2.8K', 'Intel i5 12ème gen', 'Ultra-fin 1.39kg', 'Autonomie 12h', 'LPDDR5'],
    tags: ['asus', 'zenbook', 'oled', 'i5', 'ultrabook'],
    rating: 4.7,
    reviewCount: 198,
    warranty: '2 ans constructeur',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'acer-aspire-5-ryzen7',
    name: 'Acer Aspire 5 15.6" AMD Ryzen 7',
    brand: 'Acer',
    category: 'pc',
    price: 7299.99,
    originalPrice: 7999.99,
    sku: 'ACER-A515-RYZEN7',
    description: 'Laptop Acer Aspire 5 avec processeur AMD Ryzen 7 5700U, 16GB RAM, SSD 512GB, écran FHD IPS et carte graphique Radeon intégrée pour performances équilibrées.',
    shortDescription: 'Laptop Acer Aspire 5 15.6" AMD Ryzen 7',
    images: getProductImagesByName('Acer Aspire 5 15.6" AMD Ryzen 7'),
    mainImage: getMainProductImage('Acer Aspire 5 15.6" AMD Ryzen 7'),
    inStock: true,
    stockQuantity: 28,
    specifications: {
      processeur: 'AMD Ryzen 7 5700U',
      ram: '16GB DDR4',
      stockage: 'SSD 512GB',
      ecran: '15.6" FHD IPS',
      graphique: 'AMD Radeon Graphics',
      connectivite: 'WiFi 6, USB-C'
    },
    features: ['AMD Ryzen 7', 'Écran IPS', '16GB RAM', 'SSD 512GB', 'WiFi 6', 'Excellent rapport qualité-prix'],
    tags: ['acer', 'aspire', 'ryzen7', 'ips', 'multimedia'],
    rating: 4.4,
    reviewCount: 267,
    warranty: '2 ans constructeur',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    isActive: true,
    isFeatured: false,
    promotionPercentage: 9
  },

  {
    id: 'dell-xps-13-plus-i7',
    name: 'Dell XPS 13 Plus 13.4" Intel i7',
    brand: 'Dell',
    category: 'pc',
    price: 16999.99,
    sku: 'DELL-XPS13PLUS-I7',
    description: 'Ultrabook premium Dell XPS 13 Plus avec écran InfinityEdge 13.4" 3.5K OLED, Intel Core i7-1260P, 32GB RAM et design révolutionnaire sans bordures.',
    shortDescription: 'Ultrabook premium Dell XPS 13 Plus OLED Intel i7',
    images: getProductImagesByName('Dell XPS 13 Plus 13.4" Intel i7'),
    mainImage: getMainProductImage('Dell XPS 13 Plus 13.4" Intel i7'),
    inStock: true,
    stockQuantity: 6,
    specifications: {
      processeur: 'Intel Core i7-1260P',
      ram: '32GB LPDDR5',
      stockage: 'SSD 1TB PCIe 4.0',
      ecran: '13.4" OLED 3.5K (3456x2160)',
      poids: '1.26 kg',
      design: 'InfinityEdge sans bordures'
    },
    features: ['Écran OLED 3.5K', 'Intel i7 12ème gen', '32GB RAM', 'Design premium', 'Ultra-portable'],
    tags: ['dell', 'xps', 'premium', 'oled', 'i7'],
    rating: 4.8,
    reviewCount: 87,
    warranty: '3 ans Premium Support',
    createdAt: new Date('2023-12-30'),
    updatedAt: new Date('2023-12-30'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'asus-rog-strix-g15-ryzen7',
    name: 'ASUS ROG Strix G15 Gaming Ryzen 7',
    brand: 'Asus',
    category: 'pc',
    price: 13999.99,
    sku: 'ASUS-ROG-G15-R7',
    description: 'Laptop gaming ASUS ROG Strix G15 avec AMD Ryzen 7 6800H, RTX 3060 6GB, 16GB RAM, écran 144Hz et refroidissement ROG Intelligent Cooling.',
    shortDescription: 'Laptop gaming ASUS ROG Strix G15 RTX 3060',
    images: getProductImagesByName('ASUS ROG Strix G15 Gaming Ryzen 7'),
    mainImage: getMainProductImage('ASUS ROG Strix G15 Gaming Ryzen 7'),
    inStock: true,
    stockQuantity: 11,
    specifications: {
      processeur: 'AMD Ryzen 7 6800H',
      ram: '16GB DDR5',
      stockage: 'SSD 1TB PCIe 4.0',
      ecran: '15.6" FHD 144Hz',
      graphique: 'NVIDIA RTX 3060 6GB',
      refroidissement: 'ROG Intelligent Cooling'
    },
    features: ['AMD Ryzen 7 6800H', 'RTX 3060 6GB', 'Écran 144Hz', 'DDR5', 'Refroidissement ROG'],
    tags: ['asus', 'rog', 'gaming', 'rtx3060', 'ryzen7'],
    rating: 4.7,
    reviewCount: 203,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-29'),
    updatedAt: new Date('2023-12-29'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'acer-swift-3-i5-ultrabook',
    name: 'Acer Swift 3 14" Intel i5 Ultrabook',
    brand: 'Acer',
    category: 'pc',
    price: 6799.99,
    sku: 'ACER-SWIFT3-I5-14',
    description: 'Ultrabook Acer Swift 3 avec Intel Core i5-1235U, 8GB RAM, SSD 512GB, écran IPS 14" et design ultra-fin pour mobilité et performance.',
    shortDescription: 'Ultrabook Acer Swift 3 14" Intel i5',
    images: getProductImagesByName('Acer Swift 3 14" Intel i5 Ultrabook'),
    mainImage: getMainProductImage('Acer Swift 3 14" Intel i5 Ultrabook'),
    inStock: true,
    stockQuantity: 35,
    specifications: {
      processeur: 'Intel Core i5-1235U',
      ram: '8GB LPDDR4X',
      stockage: 'SSD 512GB',
      ecran: '14" FHD IPS',
      poids: '1.25 kg',
      autonomie: 'Jusqu\'à 11h'
    },
    features: ['Intel i5 12ème gen', 'Ultra-fin 1.25kg', 'Écran IPS', 'Autonomie 11h', 'Charge rapide'],
    tags: ['acer', 'swift', 'ultrabook', 'i5', 'portable'],
    rating: 4.3,
    reviewCount: 312,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-28'),
    updatedAt: new Date('2023-12-28'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'dell-inspiron-16-plus-i7',
    name: 'Dell Inspiron 16 Plus 16" Intel i7 Créateur',
    brand: 'Dell',
    category: 'pc',
    price: 11499.99,
    sku: 'DELL-INS16PLUS-I7',
    description: 'Laptop créateur Dell Inspiron 16 Plus avec écran 16" 3K, Intel Core i7-11800H, RTX 3050 Ti, 16GB RAM, parfait pour création de contenu et design.',
    shortDescription: 'Laptop créateur Dell Inspiron 16 Plus RTX 3050 Ti',
    images: getProductImagesByName('Dell Inspiron 16 Plus 16" Intel i7 Créateur'),
    mainImage: getMainProductImage('Dell Inspiron 16 Plus 16" Intel i7 Créateur'),
    inStock: true,
    stockQuantity: 9,
    specifications: {
      processeur: 'Intel Core i7-11800H',
      ram: '16GB DDR4',
      stockage: 'SSD 512GB + HDD 1TB',
      ecran: '16" 3K (3072x1920)',
      graphique: 'NVIDIA RTX 3050 Ti 4GB',
      usage: 'Création de contenu'
    },
    features: ['Écran 16" 3K', 'Intel i7 H-series', 'RTX 3050 Ti', 'Double stockage', 'Création contenu'],
    tags: ['dell', 'inspiron', 'createur', 'rtx3050ti', 'i7'],
    rating: 4.5,
    reviewCount: 76,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-27'),
    updatedAt: new Date('2023-12-27'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'asus-vivobook-pro-16x-oled',
    name: 'ASUS Vivobook Pro 16X OLED Créateur',
    brand: 'Asus',
    category: 'pc',
    price: 14999.99,
    sku: 'ASUS-VBP16X-OLED',
    description: 'Laptop créateur ASUS Vivobook Pro avec écran OLED 16" 4K, AMD Ryzen 7 5800H, RTX 3050 Ti, DialPad et certification Pantone pour créateurs exigeants.',
    shortDescription: 'Laptop créateur ASUS Vivobook Pro 16X OLED',
    images: getProductImagesByName('ASUS Vivobook Pro 16X OLED Créateur'),
    mainImage: getMainProductImage('ASUS Vivobook Pro 16X OLED Créateur'),
    inStock: true,
    stockQuantity: 7,
    specifications: {
      processeur: 'AMD Ryzen 7 5800H',
      ram: '16GB DDR4',
      stockage: 'SSD 1TB PCIe 3.0',
      ecran: '16" OLED 4K (3840x2400)',
      graphique: 'NVIDIA RTX 3050 Ti 4GB',
      special: 'ASUS DialPad'
    },
    features: ['Écran OLED 4K', 'AMD Ryzen 7', 'RTX 3050 Ti', 'ASUS DialPad', 'Certification Pantone'],
    tags: ['asus', 'vivobook', 'oled', 'createur', 'dialpad'],
    rating: 4.6,
    reviewCount: 54,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-26'),
    updatedAt: new Date('2023-12-26'),
    isActive: true,
    isFeatured: false
  },

  // ===== ORDINATEURS DE BUREAU =====
  {
    id: 'dell-optiplex-7090-sff-i7',
    name: 'Dell OptiPlex 7090 SFF Intel i7',
    brand: 'Dell',
    category: 'ordinateurs',
    price: 9999.99,
    sku: 'DELL-OPT7090-SFF-I7',
    description: 'PC de bureau Dell OptiPlex format SFF avec Intel Core i7-11700, 16GB RAM, SSD 512GB, Windows 11 Pro et garantie entreprise pour usage professionnel.',
    shortDescription: 'PC bureau Dell OptiPlex SFF Intel i7 Windows 11 Pro',
    images: getProductImagesByName('Dell OptiPlex 7090 SFF Intel i7'),
    mainImage: getMainProductImage('Dell OptiPlex 7090 SFF Intel i7'),
    inStock: true,
    stockQuantity: 14,
    specifications: {
      processeur: 'Intel Core i7-11700',
      ram: '16GB DDR4',
      stockage: 'SSD 512GB',
      format: 'Small Form Factor',
      os: 'Windows 11 Pro',
      connectivite: 'WiFi 6, Bluetooth'
    },
    features: ['Intel i7 11ème gen', 'Format compact SFF', 'Windows 11 Pro', 'WiFi 6', 'Garantie entreprise'],
    tags: ['dell', 'optiplex', 'sff', 'i7', 'professionnel'],
    rating: 4.5,
    reviewCount: 123,
    warranty: '3 ans sur site',
    createdAt: new Date('2023-12-25'),
    updatedAt: new Date('2023-12-25'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'asus-expertcenter-d5-mini',
    name: 'ASUS ExpertCenter D5 Mini PC',
    brand: 'Asus',
    category: 'ordinateurs',
    price: 4999.99,
    sku: 'ASUS-ECD5-MINI',
    description: 'Mini PC ASUS ExpertCenter ultra-compact avec Intel Core i5-10400T, 8GB RAM, SSD 256GB, multiple ports et design silencieux pour bureau moderne.',
    shortDescription: 'Mini PC ASUS ExpertCenter Intel i5 ultra-compact',
    images: getProductImagesByName('ASUS ExpertCenter D5 Mini PC'),
    mainImage: getMainProductImage('ASUS ExpertCenter D5 Mini PC'),
    inStock: true,
    stockQuantity: 20,
    specifications: {
      processeur: 'Intel Core i5-10400T',
      ram: '8GB DDR4',
      stockage: 'SSD 256GB',
      format: 'Mini PC (0.69L)',
      ports: 'USB 3.2, HDMI, VGA',
      bruit: 'Fonctionnement silencieux'
    },
    features: ['Ultra-compact 0.69L', 'Intel i5', 'Fonctionnement silencieux', 'Multiple ports', 'Économe en énergie'],
    tags: ['asus', 'mini-pc', 'compact', 'i5', 'silencieux'],
    rating: 4.4,
    reviewCount: 89,
    warranty: '3 ans constructeur',
    createdAt: new Date('2023-12-24'),
    updatedAt: new Date('2023-12-24'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'dell-precision-3660-xeon',
    name: 'Dell Precision 3660 Workstation Intel Xeon',
    brand: 'Dell',
    category: 'ordinateurs',
    price: 24999.99,
    sku: 'DELL-PREC3660-XEON',
    description: 'Workstation Dell Precision avec processeur Intel Xeon W-1350, 32GB RAM ECC, SSD 1TB, NVIDIA RTX A2000 et certification ISV pour applications professionnelles.',
    shortDescription: 'Workstation Dell Precision Intel Xeon RTX A2000',
    images: getProductImagesByName('Dell Precision 3660 Workstation Intel Xeon'),
    mainImage: getMainProductImage('Dell Precision 3660 Workstation Intel Xeon'),
    inStock: true,
    stockQuantity: 4,
    specifications: {
      processeur: 'Intel Xeon W-1350',
      ram: '32GB DDR4 ECC',
      stockage: 'SSD 1TB NVMe',
      graphique: 'NVIDIA RTX A2000 12GB',
      certification: 'ISV certifié',
      usage: 'CAO, rendu 3D'
    },
    features: ['Intel Xeon W-1350', 'RAM ECC 32GB', 'RTX A2000', 'Certification ISV', 'Usage professionnel'],
    tags: ['dell', 'precision', 'workstation', 'xeon', 'rtx-a2000'],
    rating: 4.9,
    reviewCount: 23,
    warranty: '3 ans ProSupport',
    createdAt: new Date('2023-12-23'),
    updatedAt: new Date('2023-12-23'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'asus-rog-strix-gt35-gaming',
    name: 'ASUS ROG Strix GT35 Gaming Desktop',
    brand: 'Asus',
    category: 'ordinateurs',
    price: 18999.99,
    sku: 'ASUS-ROG-GT35-GAMING',
    description: 'PC gaming ASUS ROG Strix GT35 avec Intel Core i7-11700KF, RTX 3070 8GB, 32GB RAM, SSD 1TB, refroidissement liquide et éclairage RGB Aura Sync.',
    shortDescription: 'PC gaming ASUS ROG Strix GT35 RTX 3070',
    images: getProductImagesByName('ASUS ROG Strix GT35 Gaming Desktop'),
    mainImage: getMainProductImage('ASUS ROG Strix GT35 Gaming Desktop'),
    inStock: true,
    stockQuantity: 6,
    specifications: {
      processeur: 'Intel Core i7-11700KF',
      ram: '32GB DDR4 3200MHz',
      stockage: 'SSD 1TB + HDD 2TB',
      graphique: 'NVIDIA RTX 3070 8GB',
      refroidissement: 'Liquide ROG',
      rgb: 'Aura Sync'
    },
    features: ['Intel i7-11700KF', 'RTX 3070 8GB', '32GB RAM', 'Refroidissement liquide', 'RGB Aura Sync'],
    tags: ['asus', 'rog', 'gaming', 'rtx3070', 'rgb'],
    rating: 4.8,
    reviewCount: 145,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-22'),
    updatedAt: new Date('2023-12-22'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'acer-veriton-x-i5-business',
    name: 'Acer Veriton X Desktop Intel i5 Business',
    brand: 'Acer',
    category: 'ordinateurs',
    price: 5999.99,
    sku: 'ACER-VERITON-X-I5',
    description: 'PC de bureau Acer Veriton X pour entreprise avec Intel Core i5-10400, 8GB RAM, SSD 256GB, Windows 11 Pro et fonctionnalités de sécurité avancées.',
    shortDescription: 'PC bureau Acer Veriton X Intel i5 Business',
    images: getProductImagesByName('Acer Veriton X Desktop Intel i5 Business'),
    mainImage: getMainProductImage('Acer Veriton X Desktop Intel i5 Business'),
    inStock: true,
    stockQuantity: 25,
    specifications: {
      processeur: 'Intel Core i5-10400',
      ram: '8GB DDR4',
      stockage: 'SSD 256GB',
      os: 'Windows 11 Pro',
      securite: 'TPM 2.0, Kensington Lock',
      format: 'Desktop standard'
    },
    features: ['Intel i5-10400', 'Windows 11 Pro', 'Sécurité TPM 2.0', 'Usage professionnel', 'Fiable'],
    tags: ['acer', 'veriton', 'business', 'i5', 'securite'],
    rating: 4.2,
    reviewCount: 167,
    warranty: '3 ans sur site',
    createdAt: new Date('2023-12-21'),
    updatedAt: new Date('2023-12-21'),
    isActive: true,
    isFeatured: false
  },

  // ===== PANNEAUX SOLAIRES LG & SAMSUNG =====
  {
    id: 'lg-neon-h-370w',
    name: 'Panneau Solaire LG NeON H 370W',
    brand: 'LG',
    category: 'solaire',
    price: 2899.99,
    sku: 'LG-NEON-H-370W',
    description: 'Panneau solaire LG NeON H 370W monocristallin avec technologie CELLO, efficacité 21.4%, garantie 25 ans et résistance aux conditions extrêmes.',
    shortDescription: 'Panneau solaire LG NeON H 370W monocristallin',
    images: getProductImagesByName('Panneau Solaire LG NeON H 370W'),
    mainImage: getMainProductImage('Panneau Solaire LG NeON H 370W'),
    inStock: true,
    stockQuantity: 45,
    specifications: {
      puissance: '370W',
      technologie: 'Monocristallin CELLO',
      efficacite: '21.4%',
      dimensions: '1740×1042×40mm',
      poids: '18.5 kg',
      garantie: '25 ans performance'
    },
    features: ['370W haute puissance', 'Efficacité 21.4%', 'Technologie CELLO', 'Garantie 25 ans', 'Résistant'],
    tags: ['lg', 'neon', 'solaire', '370w', 'monocristallin'],
    rating: 4.8,
    reviewCount: 156,
    warranty: '25 ans performance, 12 ans produit',
    createdAt: new Date('2023-12-20'),
    updatedAt: new Date('2023-12-20'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'samsung-400w-bifacial',
    name: 'Panneau Samsung 400W Bifacial',
    brand: 'Samsung',
    category: 'solaire',
    price: 3199.99,
    sku: 'SAM-400W-BIFACIAL',
    description: 'Panneau solaire Samsung 400W bifacial avec cellules PERC, production des deux faces, efficacité 20.6% et technologie anti-PID pour performance maximale.',
    shortDescription: 'Panneau Samsung 400W bifacial haute efficacité',
    images: getProductImagesByName('Panneau Samsung 400W Bifacial'),
    mainImage: getMainProductImage('Panneau Samsung 400W Bifacial'),
    inStock: true,
    stockQuantity: 38,
    specifications: {
      puissance: '400W',
      type: 'Bifacial PERC',
      efficacite: '20.6%',
      production: 'Recto + verso',
      antiPID: 'Technologie anti-PID',
      tolerance: '+3W/-0W'
    },
    features: ['400W bifacial', 'Cellules PERC', 'Production recto-verso', 'Anti-PID', 'Tolérance positive'],
    tags: ['samsung', 'bifacial', '400w', 'perc', 'solaire'],
    rating: 4.7,
    reviewCount: 89,
    warranty: '25 ans performance, 12 ans produit',
    createdAt: new Date('2023-12-19'),
    updatedAt: new Date('2023-12-19'),
    isActive: true,
    isFeatured: true
  },

  {
    id: 'lg-kit-solaire-3kw',
    name: 'Kit Solaire LG 3kW Résidentiel',
    brand: 'LG',
    category: 'solaire',
    price: 18999.99,
    originalPrice: 21999.99,
    sku: 'LG-KIT-3KW-RES',
    description: 'Kit solaire résidentiel complet LG 3kW avec 8 panneaux NeON 2, onduleur, système de montage, câblage et monitoring pour autoconsommation.',
    shortDescription: 'Kit solaire LG 3kW complet pour résidentiel',
    images: getProductImagesByName('Kit Solaire LG 3kW Résidentiel'),
    mainImage: getMainProductImage('Kit Solaire LG 3kW Résidentiel'),
    inStock: true,
    stockQuantity: 12,
    specifications: {
      puissance: '3000W (3kW)',
      panneaux: '8x LG NeON 2 375W',
      onduleur: 'String 3kW inclus',
      montage: 'Rails et fixations',
      monitoring: 'Application mobile',
      production: '4500 kWh/an'
    },
    features: ['Kit complet 3kW', '8 panneaux LG', 'Onduleur inclus', 'Système montage', 'Monitoring'],
    tags: ['lg', 'kit', '3kw', 'residentiel', 'complet'],
    rating: 4.9,
    reviewCount: 67,
    warranty: '25 ans panneaux, 10 ans onduleur',
    createdAt: new Date('2023-12-18'),
    updatedAt: new Date('2023-12-18'),
    isActive: true,
    isFeatured: true,
    promotionPercentage: 14
  },

  {
    id: 'samsung-onduleur-5kw',
    name: 'Samsung Onduleur 5kW Triphasé',
    brand: 'Samsung',
    category: 'solaire',
    price: 4599.99,
    sku: 'SAM-OND-5KW-3PH',
    description: 'Onduleur Samsung 5kW triphasé avec efficacité 98.3%, monitoring WiFi, protection IP65 et garantie 12 ans pour installations solaires professionnelles.',
    shortDescription: 'Onduleur Samsung 5kW triphasé efficacité 98.3%',
    images: getProductImagesByName('Samsung Onduleur 5kW Triphasé'),
    mainImage: getMainProductImage('Samsung Onduleur 5kW Triphasé'),
    inStock: true,
    stockQuantity: 16,
    specifications: {
      puissance: '5000W triphasé',
      efficacite: '98.3%',
      entree: 'DC 200-1000V',
      sortie: 'AC 380V triphasé',
      protection: 'IP65',
      monitoring: 'WiFi intégré'
    },
    features: ['5kW triphasé', 'Efficacité 98.3%', 'Monitoring WiFi', 'Protection IP65', 'Garantie 12 ans'],
    tags: ['samsung', 'onduleur', '5kw', 'triphase', 'monitoring'],
    rating: 4.6,
    reviewCount: 34,
    warranty: '12 ans constructeur',
    createdAt: new Date('2023-12-17'),
    updatedAt: new Date('2023-12-17'),
    isActive: true,
    isFeatured: false
  },

  // ===== SYSTÈMES DE SÉCURITÉ HAGER =====
  {
    id: 'hager-centrale-alarme-8zones',
    name: 'Centrale d\'Alarme Hager 8 Zones',
    brand: 'Hager',
    category: 'securite',
    price: 1899.99,
    sku: 'HAG-CENTRALE-8Z',
    description: 'Centrale d\'alarme Hager 8 zones avec clavier LCD, transmetteur GSM, sirène intégrée et application mobile pour sécurisation complète de votre propriété.',
    shortDescription: 'Centrale alarme Hager 8 zones avec GSM',
    images: getProductImagesByName('Centrale d\'Alarme Hager 8 Zones'),
    mainImage: getMainProductImage('Centrale d\'Alarme Hager 8 Zones'),
    inStock: true,
    stockQuantity: 8,
    specifications: {
      zones: '8 zones filaires',
      clavier: 'LCD rétroéclairé',
      communication: 'GSM/SMS',
      sirene: 'Intégrée 110dB',
      alimentation: '230V + batterie',
      app: 'Mobile iOS/Android'
    },
    features: ['8 zones filaires', 'Clavier LCD', 'Transmetteur GSM', 'Sirène 110dB', 'App mobile'],
    tags: ['hager', 'alarme', '8zones', 'gsm', 'securite'],
    rating: 4.5,
    reviewCount: 78,
    warranty: '3 ans constructeur',
    createdAt: new Date('2023-12-16'),
    updatedAt: new Date('2023-12-16'),
    isActive: true,
    isFeatured: false
  },

  // ===== SYSTÈMES D'INCENDIE =====
  {
    id: 'ingelec-centrale-incendie-4zones',
    name: 'Centrale Incendie Ingelec 4 Zones',
    brand: 'Ingelec',
    category: 'incendie',
    price: 3299.99,
    sku: 'ING-CENT-INC-4Z',
    description: 'Centrale de détection incendie Ingelec 4 zones conventionnelle avec afficheur LCD, sirène intégrée et conformité EN54 pour protection incendie professionnelle.',
    shortDescription: 'Centrale incendie Ingelec 4 zones EN54',
    images: getProductImagesByName('Centrale Incendie Ingelec 4 Zones'),
    mainImage: getMainProductImage('Centrale Incendie Ingelec 4 Zones'),
    inStock: true,
    stockQuantity: 5,
    specifications: {
      zones: '4 zones conventionnelles',
      affichage: 'LCD graphique',
      norme: 'EN54-2/4 certifié',
      sirene: 'Intégrée + relais',
      alimentation: '230V + batteries',
      extension: 'Modules additionnels'
    },
    features: ['4 zones conventionnelles', 'Certifié EN54', 'LCD graphique', 'Sirène intégrée', 'Extensible'],
    tags: ['ingelec', 'incendie', '4zones', 'en54', 'detection'],
    rating: 4.7,
    reviewCount: 23,
    warranty: '5 ans constructeur',
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2023-12-15'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'hager-detecteur-fumee-tg600al',
    name: 'Hager Détecteur de Fumée TG600AL',
    brand: 'Hager',
    category: 'incendie',
    price: 299.99,
    sku: 'HAG-TG600AL-FUMEE',
    description: 'Détecteur de fumée optique Hager TG600AL avec pile lithium 10 ans, certification NF, test automatique et signal sonore 85dB pour protection résidentielle.',
    shortDescription: 'Détecteur fumée Hager pile 10 ans NF',
    images: getProductImagesByName('Hager Détecteur de Fumée TG600AL'),
    mainImage: getMainProductImage('Hager Détecteur de Fumée TG600AL'),
    inStock: true,
    stockQuantity: 150,
    specifications: {
      type: 'Optique de fumée',
      pile: 'Lithium 10 ans',
      certification: 'NF EN14604',
      signal: '85dB à 3m',
      test: 'Bouton test',
      installation: 'Plafond/mur'
    },
    features: ['Pile 10 ans', 'Certification NF', 'Signal 85dB', 'Test automatique', 'Installation facile'],
    tags: ['hager', 'detecteur', 'fumee', 'nf', '10ans'],
    rating: 4.6,
    reviewCount: 234,
    warranty: '5 ans constructeur',
    createdAt: new Date('2023-12-14'),
    updatedAt: new Date('2023-12-14'),
    isActive: true,
    isFeatured: false
  },

  // ===== MATÉRIELS ÉLECTRONIQUES =====
  {
    id: 'samsung-qled-55-4k',
    name: 'Samsung Smart TV 55" 4K QLED',
    brand: 'Samsung',
    category: 'electronique',
    price: 8999.99,
    originalPrice: 9999.99,
    sku: 'SAM-QN55Q70A-4K',
    description: 'Smart TV Samsung 55" QLED 4K avec Quantum Processor 4K, HDR10+, Tizen OS, contrôle vocal et design ultra-fin pour expérience cinéma à domicile.',
    shortDescription: 'Smart TV Samsung 55" QLED 4K HDR10+',
    images: getProductImagesByName('Samsung Smart TV 55" 4K QLED'),
    mainImage: getMainProductImage('Samsung Smart TV 55" 4K QLED'),
    inStock: true,
    stockQuantity: 12,
    specifications: {
      taille: '55 pouces (139 cm)',
      resolution: '4K UHD (3840x2160)',
      technologie: 'QLED Quantum Dot',
      hdr: 'HDR10+ adaptatif',
      os: 'Tizen Smart TV',
      audio: 'Dolby Digital Plus'
    },
    features: ['QLED 4K', 'Quantum Processor', 'HDR10+', 'Tizen OS', 'Contrôle vocal', 'Design ultra-fin'],
    tags: ['samsung', 'qled', '55pouces', '4k', 'smart-tv'],
    rating: 4.7,
    reviewCount: 289,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-13'),
    updatedAt: new Date('2023-12-13'),
    isActive: true,
    isFeatured: true,
    promotionPercentage: 10
  },

  {
    id: 'simon-82-prise-usbc',
    name: 'Prise Simon 82 avec USB Type-C',
    brand: 'Simon',
    category: 'electronique',
    price: 189.99,
    sku: 'SIM-82-USB-C',
    description: 'Prise électrique Simon 82 avec chargeur USB Type-C intégré, design moderne blanc, installation standard et charge rapide pour appareils mobiles.',
    shortDescription: 'Prise Simon 82 avec USB Type-C intégré',
    images: getProductImagesByName('Prise Simon 82 avec USB Type-C'),
    mainImage: getMainProductImage('Prise Simon 82 avec USB Type-C'),
    inStock: true,
    stockQuantity: 85,
    specifications: {
      serie: 'Simon 82',
      usb: 'Type-C + Type-A',
      puissance: '18W charge rapide',
      couleur: 'Blanc mat',
      installation: 'Encastré standard',
      norme: 'CE, NF'
    },
    features: ['USB Type-C', 'Charge rapide 18W', 'Design moderne', 'Installation standard', 'Série Simon 82'],
    tags: ['simon', 'prise', 'usb-c', 'charge', 'moderne'],
    rating: 4.4,
    reviewCount: 167,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-12'),
    updatedAt: new Date('2023-12-12'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'hager-tableau-electrique-3rangees',
    name: 'Tableau Électrique Hager 3 Rangées',
    brand: 'Hager',
    category: 'electronique',
    price: 899.99,
    sku: 'HAG-TAB-3R-54MOD',
    description: 'Tableau électrique Hager 3 rangées 54 modules avec porte transparente, borniers de terre et neutre, rail DIN et conformité NF C 15-100.',
    shortDescription: 'Tableau électrique Hager 3 rangées 54 modules',
    images: getProductImagesByName('Tableau Électrique Hager 3 Rangées'),
    mainImage: getMainProductImage('Tableau Électrique Hager 3 Rangées'),
    inStock: true,
    stockQuantity: 25,
    specifications: {
      rangees: '3 rangées',
      modules: '54 modules (18 par rangée)',
      porte: 'Transparente avec serrure',
      borniers: 'Terre et neutre inclus',
      norme: 'NF C 15-100',
      installation: 'Encastré ou saillie'
    },
    features: ['3 rangées 54 modules', 'Porte transparente', 'Borniers inclus', 'NF C 15-100', 'Installation flexible'],
    tags: ['hager', 'tableau', 'electrique', '3rangees', 'nf'],
    rating: 4.8,
    reviewCount: 145,
    warranty: '10 ans constructeur',
    createdAt: new Date('2023-12-11'),
    updatedAt: new Date('2023-12-11'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'samsung-ecran-27-qhd-curved',
    name: 'Écran Samsung 27" QHD Curved',
    brand: 'Samsung',
    category: 'electronique',
    price: 2299.99,
    sku: 'SAM-C27F396FHU-QHD',
    description: 'Moniteur Samsung 27" QHD incurvé avec dalle VA, courbure 1800R, AMD FreeSync, Eye Saver Mode et design sans bordures pour gaming et productivité.',
    shortDescription: 'Moniteur Samsung 27" QHD incurvé gaming',
    images: getProductImagesByName('Écran Samsung 27" QHD Curved'),
    mainImage: getMainProductImage('Écran Samsung 27" QHD Curved'),
    inStock: true,
    stockQuantity: 18,
    specifications: {
      taille: '27 pouces',
      resolution: 'QHD (2560x1440)',
      dalle: 'VA incurvée 1800R',
      frequence: '75Hz',
      freesync: 'AMD FreeSync',
      connectique: 'HDMI, VGA'
    },
    features: ['27" QHD incurvé', 'Dalle VA 1800R', 'AMD FreeSync', 'Eye Saver Mode', 'Sans bordures'],
    tags: ['samsung', 'moniteur', '27pouces', 'qhd', 'curved'],
    rating: 4.5,
    reviewCount: 198,
    warranty: '3 ans constructeur',
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2023-12-10'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'simon-interrupteur-82-blanc',
    name: 'Interrupteur Simon 82 Blanc Complet',
    brand: 'Simon',
    category: 'electronique',
    price: 45.99,
    sku: 'SIM-82-INT-BLANC',
    description: 'Interrupteur va-et-vient Simon série 82 blanc avec mécanisme, plaque et griffes, installation encastrée standard et finition mate élégante.',
    shortDescription: 'Interrupteur Simon 82 va-et-vient blanc',
    images: getProductImagesByName('Interrupteur Simon 82 Blanc Complet'),
    mainImage: getMainProductImage('Interrupteur Simon 82 Blanc Complet'),
    inStock: true,
    stockQuantity: 200,
    specifications: {
      serie: 'Simon 82',
      type: 'Va-et-vient',
      couleur: 'Blanc mat',
      installation: 'Encastré',
      contenu: 'Mécanisme + plaque + griffes',
      norme: 'NF, CE'
    },
    features: ['Série Simon 82', 'Va-et-vient', 'Blanc mat', 'Kit complet', 'Installation standard'],
    tags: ['simon', 'interrupteur', 'blanc', 'va-et-vient', '82'],
    rating: 4.3,
    reviewCount: 456,
    warranty: '2 ans constructeur',
    createdAt: new Date('2023-12-09'),
    updatedAt: new Date('2023-12-09'),
    isActive: true,
    isFeatured: false
  },

  {
    id: 'hager-disjoncteur-20a-c',
    name: 'Disjoncteur Hager 20A Courbe C',
    brand: 'Hager',
    category: 'electronique',
    price: 89.99,
    sku: 'HAG-MBN120-20A-C',
    description: 'Disjoncteur modulaire Hager 20A courbe C unipolaire+neutre, pouvoir de coupure 6kA, conforme NF C 61-410 pour protection circuits électriques.',
    shortDescription: 'Disjoncteur Hager 20A courbe C unipolaire+neutre',
    images: getProductImagesByName('Disjoncteur Hager 20A Courbe C'),
    mainImage: getMainProductImage('Disjoncteur Hager 20A Courbe C'),
    inStock: true,
    stockQuantity: 120,
    specifications: {
      intensite: '20A',
      courbe: 'C (10-50 In)',
      poles: 'Unipolaire + Neutre',
      coupure: '6kA',
      norme: 'NF C 61-410',
      modules: '2 modules DIN'
    },
    features: ['20A courbe C', 'Unipolaire+Neutre', 'Pouvoir coupure 6kA', 'NF C 61-410', '2 modules DIN'],
    tags: ['hager', 'disjoncteur', '20a', 'courbe-c', 'modulaire'],
    rating: 4.7,
    reviewCount: 89,
    warranty: '10 ans constructeur',
    createdAt: new Date('2023-12-08'),
    updatedAt: new Date('2023-12-08'),
    isActive: true,
    isFeatured: false
  }
];

/**
 * Produits mockés pour compatibilité avec l'existant
 * Utilise les 6 premiers produits du catalogue irelance
 */
export const MOCK_PRODUCTS: Product[] = IRELANCE_PRODUCTS.slice(0, 6).map(product => ({
  ...product,
  // Assurer la compatibilité avec l'ancien format
  image: product.mainImage,
  created_at: product.createdAt.toISOString().split('T')[0]
}));

// Export par défaut pour compatibilité
export default IRELANCE_PRODUCTS;